### ISSUE TITLE
Show list that caused the "block"

### ISSUE THREAD

**Issue by duramato** [quidsup/notrack#105]
There is an existing feature that shows which list blocked the tld/subdomain , but only for the blocked tlds afaik
I would like it to be avaiable for all lists.

**Comment by quidsup** [comment]
Technically its possible, but I don't know how best to achieve it because it takes a lot of processing power to sift through all the block lists.
As it stands currently there is a bit of lag on a RPi 2 based system after a busy day of Internet usage.

**Comment by quidsup** [comment]
Lot less processing power required with MariaDB.
I quickly threw something together, and haven't given it a thorough test.

It takes a couple of seconds longer for a full list of blocked historic sites to render on a RPi2, compared to a full list of allowed sites.
Although what am I complaining about, its still a lot faster rendering compared to older versions of NoTrack.

It might be improved moving from explode to regex?

**Comment by duramato** [comment]
![image](https://cloud.githubusercontent.com/assets/10121067/19873911/8a457c18-9fb9-11e6-9804-eb509abba4e9.png)

**Comment by duramato** [comment]
![image](https://cloud.githubusercontent.com/assets/10121067/19873972/df8dc3f6-9fb9-11e6-9d41-3c1bdcc0780b.png)

**Comment by quidsup** [comment]
Fortuanately I commented out the old code, so the report button can easily be reinstated.

I've thrown together another update, but I'm away from home at the moment and can't test it:
https://raw.githubusercontent.com/quidsup/ntrk-dev/master/queries.php

The report button should only show up on the NoTrack list. 
Invalid requests will be highlighted dark-red like before.

I implemented regex to look for site.domain and search for "*site.domain" in sql table.
Its not as acurate, but should be lighter on the processing.

**Comment by duramato** [comment]
Custom lists should also show the report button imo, so you can report a site to be blocked
All other domains not from the Notrack ones or the Custom should still have the button but with an whitelist button within the window, and no report to you button.

![image](https://cloud.githubusercontent.com/assets/10121067/19981688/d81b420e-a1fa-11e6-8b53-a5871a6e5fb9.png)

**Comment by duramato** [comment]
The report button doesn't seem to work anymore for me.

**Comment by quidsup** [comment]
Clear the browser cache

**Comment by duramato** [comment]
Yeah it's working now, i did had to wait for it to expire since i was on mobile.
