### ISSUE TITLE
Dnsmasq restart issues with wlan0

### ISSUE THREAD

**Issue by ShayBox** [quidsup/notrack#8]
This may just be a me problem, but i have hostapd hosting a wifi hotspot on the wlan0 interface getting the internet from Ethernet eth0 interface, and when i run the install.sh or sudo notrack the alst 2 lines are "
dnsmasq: unknown interface wlan0
 * Restarting DNS forwarder and DHCP server dnsmasq                      [fail]
"
The wifi works, the website works but it wont update any blacklist or whitelist things, dnsmasq refuses to start at all, when i do 
"sudo service dnsmasq start" it outputs those 2 lines, it wont auto start or anything.
you im sure its just an issue with me
but if it helps, im running Ubuntu Server 14.04.3 LTS x64 with Kodi, Multicraft, and i made sure to uninstall apache2 before installing because this uses lighttpd.

**Comment by quidsup** [comment]
If you do: echo $(ip -o link show | awk '{print $2,$9}' | grep ": UP" | cut -d ":" -f 1)
I guess it will come back with "eth0 wlan0"?

**Comment by ShayBox** [comment]
Yea, im guessing thats a problem...

**Comment by ShayBox** [comment]
Would you know how to fix that?

**Comment by quidsup** [comment]
I've added a selector to the installer to deal with multiple network devices.
That should resolve it

**Comment by ShayBox** [comment]
Thanks, trying it now

**Comment by ShayBox** [comment]
Thanks, it worked great.

**Comment by ShayBox** [comment]
Sorry again, but it didnt fix it totally, it got rid of that, but now it sais when dnsmasq tries to start, "dnsmasq: error at line 3 of /etc/dnsmasq.d/adsites.list" and it selected eth0 when installing notrack

**Comment by quidsup** [comment]
I forgot that notrack.sh script was using the same thing as the installer to get active network device. I've now got the installer to save chosen network device into config file /etc/notrack/notrack.conf
If the dns still works you can do an upgrade with: "notrack -u" 
Then re-run the installer

**Comment by ShayBox** [comment]
Yep, no more errors! thanks!
